function [importances, rf] = rank_random_forest_(data)
    x = data.X';
    y = data.y;
    rf = TreeBagger(50, x, y, ...
        PredictorSelection="interaction-curvature", ...
        OOBPredictorImportance="on", ...
        Surrogate="on", ...
        OOBPredictorImportance="on");

    importances = rf.OOBPermutedPredictorDeltaError;
end

